# Generated by Django 4.2.16 on 2024-11-21 00:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_avatar_user_date_of_birth_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermsAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all_agreed', models.BooleanField(default=False)),
                ('terms_of_service', models.BooleanField(default=False)),
                ('privacy_policy', models.BooleanField(default=False)),
                ('agreed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
