# Generated by Django 4.2.16 on 2024-11-23 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssetInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('market_category', models.CharField(blank=True, max_length=50, null=True)),
                ('asset_category', models.CharField(blank=True, max_length=50, null=True)),
                ('default', models.CharField(blank=True, max_length=20, null=True)),
                ('stock_options', models.CharField(blank=True, max_length=20, null=True)),
                ('bond_option1', models.CharField(blank=True, max_length=20, null=True)),
                ('bond_option2', models.CharField(blank=True, max_length=20, null=True)),
                ('bond_option3', models.CharField(blank=True, max_length=20, null=True)),
                ('bond_option4', models.CharField(blank=True, max_length=20, null=True)),
                ('bond_option5', models.CharField(blank=True, max_length=20, null=True)),
                ('bond_option6', models.CharField(blank=True, max_length=20, null=True)),
                ('bond_option7', models.CharField(blank=True, max_length=20, null=True)),
                ('industry_1', models.CharField(blank=True, max_length=50, null=True)),
                ('industry_2', models.CharField(blank=True, max_length=50, null=True)),
                ('industry_3', models.CharField(blank=True, max_length=50, null=True)),
                ('industry_4', models.CharField(blank=True, max_length=50, null=True)),
                ('risk_level', models.CharField(max_length=20)),
                ('manager', models.CharField(max_length=100)),
            ],
        ),
    ]
