# Generated by Django 4.2.16 on 2024-11-22 03:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_rate', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exchangerate',
            options={'ordering': ['-date', 'base_currency', 'target_currency']},
        ),
        migrations.AddField(
            model_name='exchangerate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='데이터 수정 시간'),
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='base_currency',
            field=models.CharField(help_text='기준 통화 (예: USD, KRW, JPY, EUR)', max_length=3, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='데이터 생성 시간'),
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='date',
            field=models.DateField(help_text='환율 기준일'),
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='rate',
            field=models.DecimalField(decimal_places=10, help_text='환율', max_digits=20),
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='target_currency',
            field=models.CharField(help_text='대상 통화 (예: USD, KRW, JPY, EUR)', max_length=3, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
        migrations.AddIndex(
            model_name='exchangerate',
            index=models.Index(fields=['base_currency', 'target_currency', 'date'], name='exchange_ra_base_cu_6cca60_idx'),
        ),
        migrations.AddIndex(
            model_name='exchangerate',
            index=models.Index(fields=['date'], name='exchange_ra_date_36c6a6_idx'),
        ),
    ]
