# Generated by Django 4.2.16 on 2024-11-23 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='bank',
            name='maps_bank_latitud_2febdb_idx',
        ),
        migrations.RemoveField(
            model_name='bank',
            name='address',
        ),
        migrations.RemoveField(
            model_name='bank',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='bank',
            name='road_address',
        ),
        migrations.RemoveField(
            model_name='bank',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='bank',
            name='location',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='bank',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='bank',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
